# Generated by Django 4.0.4 on 2022-04-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_order_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryFood',
            new_name='Category',
        ),
    ]
