# Generated by Django 4.0.4 on 2022-05-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_rename_categoryfood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
