# Generated by Django 4.0.4 on 2022-05-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_hall_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='regulation',
            name='time_frame',
        ),
        migrations.AlterField(
            model_name='dateoforganization',
            name='shift',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Buổi sáng'), (1, 'Buổi trưa'), (2, 'Buổi tối')], default=0),
        ),
        migrations.DeleteModel(
            name='TimeFrame',
        ),
    ]
