# Generated by Django 4.0.4 on 2022-05-01 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_remove_regulation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='dateofo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wedding.dateoforganization'),
        ),
    ]
