# Generated by Django 4.0.4 on 2022-05-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_remove_regulation_change_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='morning_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='night_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='noon_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
