# Generated by Django 4.0.4 on 2022-05-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_hall_morning_price_hall_night_price_hall_noon_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOrganize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hall',
            name='dateofo',
        ),
        migrations.AddField(
            model_name='hall',
            name='time_organize',
            field=models.ManyToManyField(through='wedding.HallOrganize', to='wedding.dateoforganization'),
        ),
        migrations.AddField(
            model_name='hallorganize',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.hall'),
        ),
        migrations.AddField(
            model_name='hallorganize',
            name='time_organize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.dateoforganization'),
        ),
    ]
