# Generated by Django 4.0.4 on 2022-05-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_hallorganize_remove_hall_dateofo_hall_time_organize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_of_organization',
            new_name='time_organize',
        ),
        migrations.AlterUniqueTogether(
            name='dateoforganization',
            unique_together={('date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='hallorganize',
            unique_together={('hall', 'time_organize')},
        ),
    ]
