# Generated by Django 4.0.4 on 2022-05-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='foods/%Y/%m'),
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(to='wedding.food'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedding.menu'),
        ),
    ]
